title: 'Trust me, I am an Engineer! lozinskyi.github.io'
description: "Trust me, I am an Engineer;"
baseurl: "/"
url: "https://lozinskyi.github.io"

header_pages:
  - index.md
  - contact.md

style: dark

footer: 'Trust me, I am an Engineer ;) ...and follow me on sociall:
    <a href="https://twitter.com/one_more_pol" target="_blank"><i class="nes-icon twitter is-small"></i></a> 
    <a href="https://www.linkedin.com/in/pavlo-lozynskyi-00b21561/" target="_blank"><i class="nes-icon linkedin is-small"></i></a>
    <a href="https://github.com/lozynskyi" target="_blank"><i class="nes-icon github is-small"></i></a>'

# Build settings
markdown: kramdown
remote_theme: lozynskyi/jekyll-theme-console
