title: 'lozinskyi.github.io'
description: "“Engineers like to solve problems. If there are no problems handily available, they will create their own problems.” - Scott Adams"
baseurl: "/"
url: "https://lozinskyi.github.io"

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

footer: 'follow me on <a href="https://www.instagram.com/i.m.pavlo/">instagram</a>'

# Build settings
markdown: kramdown
remote_theme: lozynskyi/jekyll-theme-console
