title: 'Trust me, I'm an Engineer! lozinskyi.github.io'
description: "Trust me, I'm an Engineer!"
baseurl: "/"
url: "https://lozinskyi.github.io"

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

footer: 'Trust me, I'm an Engineer, and follow me on <a href="https://twitter.com/one_more_pol">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: lozynskyi/jekyll-theme-console
